name: Build & Publish to Release

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Dependency
        run: go get

      - name: Create Build Directory
        run: mkdir build

      - name: Build for Darwin
        run: GOOS=darwin GOARCH=amd64 go build -o build/server_darwin_x64

      - name: Build for Linux x64
        run: GOOS=linux GOARCH=amd64 go build -o build/server_linux_x64

      - name: Build for Linux x86
        run: GOOS=linux GOARCH=386 go build -o build/server_linux_x86

      - name: Build for Windows x64
        run: GOOS=windows GOARCH=amd64 go build -o build/server_windows_x64.exe

      - name: Build for Windows x86
        run: GOOS=windows GOARCH=386 go build -o build/server_windows_x86.exe

  zip:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: DEBUG check files
        run: ls -alh

      - name: Zip Build file for Darwin
        run: zip server_darwin_x64.zip build/server_darwin_x64

      - name: Zip Build file for Linux x64
        run: zip server_linux_x64.zip build/server_linux_x64

      - name: Zip Build file for Linux x86
        run: zip server_linux_x86.zip build/server_linux_x86

      - name: Zip Build file for Windows x64
        run: zip server_windows_x64.exe.zip build/server_windows_x64.exe

      - name: Zip Build file for Windows x86
        run: zip server_windows_x86.exe.zip build/server_windows_x86.exe

  release:
    runs-on: ubuntu-latest
    needs: [zip]
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: 'build/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
